# 一、ndarray


## 1.ndarray特性
### 多维性

In [1]:
from email.policy import default
from statistics import median

import numpy as np
from numpy.ma.core import sqrt

In [2]:
arr = np.array(5) #创建0维数组
print(arr)
print('arr的维度是：',arr.ndim) #number of dimensions

5
arr的维度是： 0


In [65]:
arr = np.array([1,2,3]) #创建1维数组
print(arr)
print('arr的维度是：',arr.ndim) #number of dimensions

[1 2 3]
arr的维度是： 1


In [66]:
arr = np.array([[1,2,3],[4,5,6]]) #创建2维数组
print(arr)
print('arr的维度是：',arr.ndim) #number of dimensions

[[1 2 3]
 [4 5 6]]
arr的维度是： 2


### 同质性

In [67]:
arr = np.array([1,'hello']) #不同类型的数据类型会被强制转换成相同的数据类型
print(arr)

['1' 'hello']


In [68]:
arr = np.array([1,2.5]) #不同类型的数据类型会被强制转换成相同的数据类型
print(arr)

[1.  2.5]


## 2.ndarray的属性

In [69]:
arr = np.array(1)
print(arr)
print('数组的形状是：',arr.shape)
print('arr的维度是：',arr.ndim)
print('arr的元素个数是：',arr.size)
print('arr的元素类型是：',arr.dtype)

1
数组的形状是： ()
arr的维度是： 0
arr的元素个数是： 1
arr的元素类型是： int64


In [77]:
arr = np.array([1,2.5,3])
print(arr)
print('数组的形状是：',arr.shape)
print('arr的维度是：',arr.ndim)
print('arr的元素个数是：',arr.size)
print('arr的元素类型是：',arr.dtype)
print('arr的单元素占用的内存字节数是：',arr.itemsize)

[1.  2.5 3. ]
数组的形状是： (3,)
arr的维度是： 1
arr的元素个数是： 3
arr的元素类型是： float64
arr的单元素占用的内存字节数是： 8


In [84]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print('数组的形状是：',arr.shape)
print('arr的维度是：',arr.ndim)
print('arr的元素个数是：',arr.size)
print('arr的元素类型是：',arr.dtype)
print('arr的转置是：',arr.T)
print('arr的单元素占用的内存字节数是：',arr.itemsize)
print('arr的总占内存字节数是：',arr.nbytes)
print('arr的内存存储方式是：',arr.flags)

[[1 2 3]
 [4 5 6]]
数组的形状是： (2, 3)
arr的维度是： 2
arr的元素个数是： 6
arr的元素类型是： int64
arr的转置是： [[1 4]
 [2 5]
 [3 6]]
arr的单元素占用的内存字节数是： 8
arr的总占内存字节数是： 48
arr的内存存储方式是：   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



## 3.ndarray的创建

In [89]:
# 基础的创建
list1 = [1,5,8]
arr = np.array(list1,dtype=np.float64) #将其转化为浮点型
print(arr)

[1. 5. 8.]


In [91]:
#copy
arr1 = np.copy(arr)
print(arr1)
arr1[0]=9
print(arr1)
print(arr)

[1. 5. 8.]
[9. 5. 8.]
[1. 5. 8.]


In [136]:
# 预定义形状
# 全0 全1 未初始化 固定值
# 全0
arr = np.zeros((4,3),dtype=int)
print(arr)
# 全1
arr = np.ones((3,3),dtype=int)
print(arr)
#未初始化
arr = np.empty((3,3))
print(arr)
#固定值
arr = np.full((4,3),2)
print(arr)

[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[2 2 2]
 [2 2 2]
 [2 2 2]
 [2 2 2]]


In [91]:
arr = np.empty((5,3),dtype=int) #数组元素随机
print(arr)

[[ 98393405817455  98393405817455  98393405817455]
 [ 98393405817455  98393405817455  98393405817455]
 [ 98393405817455  98393405817455  98393405817455]
 [ 98393405817455  98393405817455  98393405817455]
 [ 98393405817455 133865540701976 133865540701976]]


In [92]:
arr1 = np.zeros_like(arr)
print(arr1)
arr1 = np.ones_like(arr)
print(arr1)
arr1 = np.empty_like(arr)
print(arr1)
arr1 = np.full_like(arr,2021)
print(arr1)


[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[2021 2021 2021]
 [2021 2021 2021]
 [2021 2021 2021]
 [2021 2021 2021]
 [2021 2021 2021]]


In [152]:
# 等差数列
arr = np.arange(1,10,2) #start end step
arr1 = np.arange(1,10,1)
print(arr)
print(arr1)

[1 3 5 7 9]
[1 2 3 4 5 6 7 8 9]


In [153]:
# 等间隔数列
arr = np.linspace(1,11,5)
print(arr)

[ 1.   3.5  6.   8.5 11. ]


In [157]:
# 对数间隔数列
arr = np.logspace(0,3,2,base=2,dtype=int) #0到3分两份，低为2
print(arr)

[1 8]


In [164]:
# 特殊矩阵
# 单位矩阵
arr = np.eye(3,2,dtype=int)
print(arr)
# 对角矩阵
arr = np.diag([5,9,5,4,4])
print(arr)
# 随机数组的生成
# 生成0到1之间的随机浮点数（均匀分布）
arr = np.random.rand(3,3)
print(arr)
# 生成指定范围区间的随机浮点数
arr = np.random.uniform(2,5,(3,3))
print(arr)

[[1 0]
 [0 1]
 [0 0]]
[[5 0 0 0 0]
 [0 9 0 0 0]
 [0 0 5 0 0]
 [0 0 0 4 0]
 [0 0 0 0 4]]
[[0.42907925 0.70504312 0.11093969]
 [0.81576584 0.80289583 0.44127321]
 [0.83393703 0.45155634 0.31082872]]
[[2.06242505 4.25990513 2.66558847]
 [2.0485848  3.89063348 3.73857226]
 [3.73560834 3.45917049 2.23721813]]


In [173]:
# 生成指定范围区间的随机整数
arr = np.random.randint (2,5,(3,3))
print(arr)

[[4 3 4]
 [3 2 4]
 [4 4 4]]


In [174]:
# 生成随机数列（正态分布）(-3,3)
arr = np.random.randn(3,3)
print(arr)

[[-0.35624496 -0.08877759 -0.85766562]
 [ 0.36418    -1.47861396 -1.58513202]
 [-1.44943807 -1.65390837  1.13960579]]


In [189]:
# 设置随机种子
np.random.seed(200)
arr = np.random.randint(1,10,(3,3))
print(arr)

[[1 5 8]
 [7 9 2]
 [8 4 2]]


## 4.ndarray的数据类型
布尔类型：bool

整数类型：int uint

浮点数：float

复数：complex

In [191]:
arr = np.array([0,1,2,-1],dtype=bool)
print(arr)

[False  True  True  True]


## 5.索引与切片

In [194]:
# 一维数组的索引与切片
arr = np.random.randint(1,100,20)
print(arr)

[28 93 44 47 34 46 16 82 30 73 65 28 72 30 33 64 44 88 26 66]


In [202]:
print(arr[0])
print(arr[:]) # 获取全部数据
print(arr[1:5])
print(arr[slice(1,5)])
print(arr[slice(2,15,3)])
print(arr[arr>30]) # 布尔索引

28
[28 93 44 47 34 46 16 82 30 73 65 28 72 30 33 64 44 88 26 66]
[93 44 47 34]
[93 44 47 34]
[44 46 30 28 33]
[93 44 47 34 46 82 73 65 72 33 64 44 88 66]


In [203]:
# 二维数组的索引与切片
arr = np.random.randint(1,100,(4,4))
print(arr)

[[96 85 34 22]
 [13 43 46 16]
 [56 51 97 16]
 [62 43 10 75]]


In [215]:
print(arr[0])
print(arr[1,3])
print(arr[::]) # 获取全部数据
print(arr[1,:])
print(arr[1,2:3])
print(arr[1:2])
print(arr[slice(1,2)])
print(arr[slice(2,15,3)])
print(arr[2][arr[2]>30]) # 布尔索引
print(arr[:,2]) # 取列

[96 85 34 22]
16
[[96 85 34 22]
 [13 43 46 16]
 [56 51 97 16]
 [62 43 10 75]]
[13 43 46 16]
[46]
[[13 43 46 16]]
[[13 43 46 16]]
[[56 51 97 16]]
[56 51 97]
[34 46 97 10]


## 6.ndarray的运算

In [5]:
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [7]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[10,11,12]])
print(a+b)
print(a-b)
print(a*b)

[[ 5  7  9]
 [11 13 15]
 [17 19 21]]
[[-3 -3 -3]
 [-3 -3 -3]
 [-3 -3 -3]]
[[  4  10  18]
 [ 28  40  54]
 [ 70  88 108]]


In [9]:
# 广播机制
# 同一维度：相同，1
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a+b)
'''a
1 2 3
1 2 3
1 2 3
b
4 4 4
5 5 5
6 6 6'''

[[5 6 7]
 [6 7 8]
 [7 8 9]]


In [11]:
a = np.array([1,2,3])
b = np.array([[4,5]])
print(a+b)

ValueError: operands could not be broadcast together with shapes (3,) (1,2) 

In [12]:
# 矩阵的运算
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([[4,5,6],[7,8,9],[10,11,12]])
print(a@b)

[[ 48  54  60]
 [111 126 141]
 [174 198 222]]


# 二、numpy常用函数
## 1.基本数学函数

In [15]:
# 计算平方根:sqrt
print(np.sqrt(16))
arr = np.array([1,4,9])
print(np.sqrt(arr))

4.0
[1. 2. 3.]


In [16]:
# 计算指数:exp
print(np.exp(0))
print(np.exp(1))

1.0
2.718281828459045


In [25]:
# 计算自然对数：log   (lnx)
print(np.log(2.71))

0.9969486348916096


In [19]:
# 计算三角函数值：sin cos
print(np.sin(np.pi/2))
print(np.cos(np.pi))

1.0
-1.0


In [ ]:
# 计算绝对值：abs

In [ ]:
# 计算a的b次幂：power

In [ ]:
# 计算四舍五入：round

In [ ]:
# 向上取整：ceil 向下取整：floor

In [17]:
# 检测缺失值：NaN
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

## 2.统计函数
### 求和、计算平均值、计算中位数、标准差、方差
### 查找最大值、最小值
### 计算分位数、累计和、累计积

In [27]:
arr = np.random.randint(1,20,8)
print(arr)

[19 13  1 12 11 19 14  8]


In [29]:
# 求和
print(np.sum(arr))

97


In [30]:
# 计算平均值
print(np.mean(arr))

12.125


In [31]:
# 计算中位数
print(np.median(arr))

12.5


In [33]:
# 计算标准差、方差
print(np.var(arr)  # 方差
print(np.std(arr)) # 标准差

30.109375
5.4872010169119925


In [35]:
# 计算最大值、最小值
print(np.max(arr),np.argmax(arr)) #索引值
print(np.min(arr),np.argmin(arr))

19 0
1 2


In [41]:
# 分位数
print(arr)
print(np.percentile(arr,60))
# 0.6*7=4.2  7为间隔数，0.6为上述60%
# 1 8 11 12 13 14 19 19
# (14-13)*0.2+13=13.2    0.6所在的区间范围为（13，14） ，0.2为4.2-4

[19 13  1 12 11 19 14  8]
13.2


In [44]:
# 累计和、累计积
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

97
[19 32 33 45 56 75 89 97]
[      19      247      247     2964    32604   619476  8672664 69381312]


## 3.比较函数
### 比较是否大于、小于、等于
### 逻辑语与、或、非
### 检查数组中是否有一个True、是否所有的都为True,自定义条件

In [48]:
# 是否大于
print(np.greater([3,4,5,8,9],5))
# 是否小于
print(np.less([3,4,5,8,9],5))
# 是否等于
print(np.equal([3,4,5,8,9],5))
print(np.equal([3,4,5,8,9],[5,4,5,4,9]))

[False False False  True  True]
[ True  True False False False]
[False False  True False False]
[False  True  True False  True]


In [59]:
# 与
print(np.logical_and([0,1],[1,1]))
# 或
print(np.logical_or([0,1],[1,1]))
print(np.logical_or([0,0],[0,1]))
# 非
print(np.logical_not([0,1]))

[False  True]
[ True  True]
[False  True]
[ True False]


In [62]:
# 检查是否有一个元素为True
print(np.any([0,1,0,0,1]))
# 检查是否全部元素为True
print(np.all([0,1,0,0,1]))

True
False


In [64]:
# 自定义条件
# print(np.where(条件,符合条件,不符合条件))
arr = np.array([5,4,8,1,6])
print(np.where(arr<4,arr,4))

[4 4 4 1 4]


In [65]:
arr = np.array([5,4,8,1,6])
print(np.where(arr<4,8,4))

[4 4 4 8 4]


In [67]:
score = np.random.randint(1,100,15)
print(score)
print(np.where(score<60,"不及格","及格"))

[69 72 92 61 58 62 86 94 15 35 49 78 99 45  3]
['及格' '及格' '及格' '及格' '不及格' '及格' '及格' '及格' '不及格' '不及格' '不及格' '及格' '及格'
 '不及格' '不及格']


In [68]:
score = np.random.randint(1,100,15)
print(score)
print(np.where
      (score<60,"不及格",np.where(
          score<80,"良好","优秀")
       ))

[15 50 51  1 31 58 36 50 41  4 72  6 54 92 96]
['不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '良好' '不及格'
 '不及格' '优秀' '优秀']


In [72]:
# np.select(条件，要返回的结果)
print(np.select([score<60,(score>60)&(score<80),score>80],
                ["不及格","良好","优秀"],
                default = "未知"))

['不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '不及格' '良好' '不及格'
 '不及格' '优秀' '优秀']


In [80]:
# 排序函数
np.random.seed(0)
arr = np.random.randint(1,100,15)
print(arr)
print(np.sort(arr))

[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59]
[10 13 22 37 45 48 59 65 68 68 71 84 88 89 89]


In [81]:
# 去重函数
print(np.unique(arr))

[10 13 22 37 45 48 59 65 68 71 84 88 89]


In [82]:
# 数组的拼接
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate([a,b]))

[1 2 3 4 5 6]


In [85]:
# 数组的分割
print(np.split(arr,[2,5,8]))

[array([45, 48], dtype=int32), array([65, 68, 68], dtype=int32), array([10, 84, 22], dtype=int32), array([37, 88, 71, 89, 89, 13, 59], dtype=int32)]


In [90]:
# 调整数组形状
arr = np.random.randint(1,100,9)
print(np.reshape(arr,[3,3]))

[[66 40 88]
 [47 89 82]
 [38 26 78]]


# 二、Numpy科学计算综合练习

### eg.1

In [100]:
high_tem = np.array([28,30,29,31,32,30,29])
print('平均气温:',np.mean(high_tem))
print('最高气温:',np.max(high_tem),np.argmax(high_tem))
print('最低气温:',np.min(high_tem),np.argmin(high_tem))
print('气温超过30°的天数:',len(high_tem[high_tem>30]))

平均气温: 29.857142857142858
最高气温: 32 4
最低气温: 28 0
气温超过30°的天数: 2


In [112]:
print('气温超过30°的天数:',np.cumsum(np.where(high_tem>30,1,0))[-1])

气温超过30°的天数: 2


### eg.2

In [117]:
score = np.array([85,90,78,92,88])
print(score)
print('平均成绩为:',np.mean(score))
print('中位数为:',np.median(score))
print('标准差为:%.3f'% np.std(score))
print('转化为十分制为:',score/10)

[85 90 78 92 88]
平均成绩为: 86.6
中位数为: 88.0
标准差为:4.883
转化为十分制为: [8.5 9.  7.8 9.2 8.8]


### eg.3

In [127]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print('A+B=\n', A+B)
print('A*B=\n',A*B)
print('A与B的矩阵乘积:\n',A@B)

A+B=
 [[ 6  8]
 [10 12]]
A*B=
 [[ 5 12]
 [21 32]]
A与B的矩阵乘积:
 [[19 22]
 [43 50]]


### eg.4

In [158]:
np.random.seed(0)
arr = np.random.randint(0,10,(3,4))
print(arr)
for i in range(len(arr)):
    print(f'第{i+1}行的最小值为：',np.min(arr[i]))
arr1 = arr.T
print(arr1)
for j in range(len(arr1)):
    print(f'第{j+1}列的最大值为：',np.max(arr1[j]))   # np.max(arr,axis=0) axis=0为上下处理axis=1为左右处理
arr2 = np.where(arr%2 ==1,-1,arr)
print(arr2 )
arr[arr%2==1]=-1
print(arr)

[[5 0 3 3]
 [7 9 3 5]
 [2 4 7 6]]
第1行的最小值为： 0
第2行的最小值为： 3
第3行的最小值为： 2
[[5 7 2]
 [0 9 4]
 [3 3 7]
 [3 5 6]]
第1列的最大值为： 7
第2列的最大值为： 9
第3列的最大值为： 7
第4列的最大值为： 6
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]
[[-1  0 -1 -1]
 [-1 -1 -1 -1]
 [ 2  4 -1  6]]


### eg.5

In [175]:
arr1 = np.arange(1,13,1)
print(arr1)
arr2 = np.copy(arr1.reshape(3,4))
print(arr2)
sum = np.sum(arr2,axis=1)
print(sum)
med = np.mean(arr2,axis=0)
print(med)
arr3 = np.reshape(arr2,(12))
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[10 26 42]
[5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


### eg.6

In [190]:
np.random.seed(0)
arr = np.random.randint(0,20,(5,5))
print(arr)
print(arr[arr>10])
print(np.where(arr>10,arr,0))


[[12 15  0  3  3]
 [ 7  9 19 18  4]
 [ 6 12  1  6  7]
 [14 17  5 13  8]
 [ 9 19 16 19  5]]
[12 15 19 18 12 14 17 13 19 16 19]
[[12 15  0  0  0]
 [ 0  0 19 18  0]
 [ 0 12  0  0  0]
 [14 17  0 13  0]
 [ 0 19 16 19  0]]


### eg.7

In [193]:
sale = np.array([120,135,110,125,130,140])
print(np.sum(sale))
print(np.mean(sale))
print(np.var(sale))
print(np.max(sale),np.argmax(sale))
print(np.min(sale),np.argmin(sale))

760
126.66666666666667
97.22222222222223
140 5
110 2


### eg.8

In [195]:
A = np.array([1,2,3])
B = np.array([4,5,6])
print(np.concatenate([A,B]))
print(np.array([A,B]))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


### eg.9

In [208]:
arr = np.array([2,1,2,3,1,4,3])
print(np.unique(arr))
arr1,counts = np.unique(arr,return_counts=True)
print(counts)
d = []
for i in range(len(arr1)):
    d = d + [len(arr[arr==arr1[i]])]
print(d)

[1 2 3 4]
[2 2 2 1]
[2, 2, 2, 1]


### eg.10

In [220]:
sale = np.array([20,25,22,30,28])
money = np.array([15,18,16,22,20])
lirun = sale - money
print(lirun)
print(np.mean(lirun))
print(np.std(lirun))
print(len(lirun[lirun==np.max(lirun)]))

[5 7 6 8 8]
6.8
1.16619037896906
2
